#!/bin/bash
g++ -std=c++23 -DLOCAL -Wshadow -Wall -g -fsanitize=address \
 -fsanitize=undefined -D_GLIBCXX_DEBUG -fmax-errors=2 code.cpp\
 -o a.out || { echo "Compilation failed!"; exit 1; }
echo
echo Input:
cat $1
echo
echo Output:
./a.out < $1
echo